=== fabianGomez0286/bryansCafe/data/menu.dtd
<!ELEMENT menu (meal+, beverage+)>
<!ELEMENT meal (name, price, description, image)>
<!ELEMENT beverage (type, (size | name), price, description?)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT image (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT size (#PCDATA)>

=== fabianGomez0286/bryansCafe/data/menu.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE menu SYSTEM "menu.dtd">
<menu>
    <meal>
        <name>Beetroot and feta salad</name>
        <price>$15.00</price>
        <description>Suitable for vegetarians, made with fresh beetroot</description>
        <image>images/beetroot_feta_salad.jpg</image>
    </meal>
    <meal>
        <name>Sourdough Rye Sandwich</name>
        <price>$18.00</price>
        <description>Cheese and salad sandwich made with organic, sourdough rye bread</description>
        <image>images/sourdough_rye_sandwich.jpg</image>
    </meal>
    <meal>
        <name>Spinach Pie and Salad</name>
        <price>$20.00</price>
        <description>Tasty pie with salad</description>
        <image>images/spinach_pie_salad.jpg</image>
    </meal>
    <meal>
        <name>Feta pancakes with salad</name>
        <price>$19.50</price>
        <description>Tasty pancake filled with feta and salad</description>
        <image>images/feta_pancakes.jpg</image>
    </meal>
    
    <beverage>
        <type>coffee</type>
        <size>Small</size>
        <price>$3.50</price>
        <description>For coffee, please inform the staff of the coffee type.</description>
    </beverage>
    <beverage>
        <type>coffee</type>
        <size>Regular</size>
        <price>$4.00</price>
        <description>For coffee, please inform the staff of the coffee type.</description>
    </beverage>
    <beverage>
        <type>coffee</type>
        <size>Large</size>
        <price>$4.50</price>
        <description>For coffee, please inform the staff of the coffee type.</description>
    </beverage>
    <beverage>
        <type>other</type>
        <name>Soda</name>
        <price>$3.00</price>
    </beverage>
    <beverage>
        <type>other</type>
        <name>Fresh juice</name>
        <price>$6.00</price>
    </beverage>
    <beverage>
        <type>other</type>
        <name>Bottled water</name>
        <price>$2.00</price>
    </beverage>
</menu>
